mysite/memories/urls.py
from django.conf.urls import url
from django.urls import path

from . import views


app_name = 'memories'
urlpatterns = [
    # ex: /

    url('account/', views.personal_account, name='personal_account'),
    url('save_memory/', views.save_memory, name='save_memory'),
    url('add_memory/', views.form_add_memory, name='form_add_memory'),
    url('', views.index, name='index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('memories.urls')),
    path('admin/', admin.site.urls),
]

mysite/memories/models.py
import datetime

from django.db import models
from django.utils import timezone

class User(models.Model):
    """
    Имя и фотография пользователя подтягиваются из facebook.
    """
    name = models.CharField(max_length=255)
    path_photo = models.TextField()

    def __str__(self):
        return self.name


class Memory(models.Model):
    """
    Воспомининие пользователя включает название, координаты места
    (location_latitude - широта, location_longitude - долгота),
    коментарий и дату публикации.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    location_name = models.CharField(max_length=225)
    location_latitude = models.DecimalField(decimal_places=3, max_digits=8)
    location_longitude = models.DecimalField(decimal_places=3, max_digits=8)
    comment = models.TextField()

    def __str__(self):
        return self.location_name

mysite/memories/forms.py
from django import forms


class AddMemoryForm(forms.Form):
    geo_point = forms.CharField(label='Координаты места',
                                max_length=30,
                                widget=forms.TextInput(attrs={'id': "point",
                                                              'class': "form-control",
                                                              'readonly': '',
                                                              'title': "Выбирите место на карте"}))
    location_name = forms.CharField(label='Название',
                                    max_length=255,
                                    widget=forms.TextInput(attrs={'class': "form-control"}))
    comment = forms.CharField(label='Описание',
                              widget=forms.Textarea(attrs={'class': "form-control"}))

mysite/memories/views.py
import logging

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils import timezone
from django.urls import reverse

from .models import Memory
from .forms import AddMemoryForm


def index(request):
    # Главная страница. Описание сайта и вход через facebook
    template = 'memories/index.html'
    title = "Добро пожаловать!"
    context = {'title': title}
    return render(request, template, context)


def personal_account(request):
    # Личный кабинет со списком воспоминаний или сообщением об их отсутствии
    latest_memories_list = Memory.objects.all()
    template = 'memories/user.html'
    title = "Ваши воспоминания"
    context = {
        'latest_memories_list': latest_memories_list,
        'title': title
    }
    return render(request, template, context)


def form_add_memory(request):
    # Форма добавления воспоминания
    template = 'memories/add_memory.html'
    title = "Добавление воспоминания"
    form = AddMemoryForm()
    context = {'title': title, 'form': form}
    return render(request, template, context)


def save_memory(request):
    # Проверка запонениия формы и сохранение воспоминания в БД
    if request.method == 'POST':
        form = AddMemoryForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['geo_point']:
                location_latitude, location_longitude, location_name, comment = get_new_nemory(form)
                save_new_memory_in_database(location_latitude, location_longitude, location_name, comment)
                return HttpResponseRedirect(reverse('memories:personal_account'))
    else:
        form = AddMemoryForm()
    return render(request, 'memories/add_memory.html', {
                'error_message': "Выберите место на карте",
                'form': form,
                })


def get_new_nemory(form):
    # Получает новое воспоминание (координаты, название и комментарий) из формы.
    # Возвращает координаты, название и комментарий нового воспоминания
    geo_point = form.cleaned_data['geo_point']
    location_latitude, location_longitude = geo_point.split(',')
    location_name = form.cleaned_data['location_name']
    comment = form.cleaned_data['comment']
    return location_latitude, location_longitude, location_name, comment


def save_new_memory_in_database(location_latitude,
                                location_longitude,
                                location_name,
                                comment):
    # Сохраняет координаты, название и комментарий нового воспоминания в БД
    # Пока приписывает новые воспоминания конкретному пользователю (user_id=1)
    memory = Memory(
        location_latitude=location_latitude,
        location_longitude=location_longitude,
        location_name=location_name,
        comment=comment,
        user_id=1,
    )
    memory.save()

mysite/memories/templates/base.html
<!doctype html>
<html lang="ru">
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{{ title }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    {% block script %} {% endblock %}
</head>
    {% block content %} {% endblock %}

	<!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>
</html>

mysite/memories/templates/memories/add_memory.html
{% extends "base.html" %}

{% block script %}
<script src="https://api-maps.yandex.ru/1.1/index.xml" type="text/javascript"></script>

<script type="text/javascript" charset="utf-8">
		 var map;
		 function init () {
		   map = new YMaps.Map( document.getElementById("YMapsID") );
		   map.setCenter(new YMaps.GeoPoint(60.598469,56.835981), 15,
				  YMaps.MapType.MAP);

YMaps.Events.observe(map, map.Events.Click, function (map, mEvent) {
                var myHtml = "Значение: " + mEvent.getGeoPoint() +
					"<br>";
                map.openBalloon(mEvent.getGeoPoint(), myHtml);
                document.getElementById('point').value = mEvent.getGeoPoint();
});
            map.addControl(new YMaps.TypeControl());
            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
}
</script>
{% endblock %}

{% block content %}
<body onload="init();">
<h2 align="center">
	Добавление воспоминаний
</h2>
<div class="container">
	<div class="row">
		<p>
			Выберите место на карте и введите название и описание
		</p>
	</div>
</div>
	<div class="container">
	  <div class="row">
		<div class="col">
			<div id="YMapsID" style="width:600px; height:400px;"></div>
			<p></p>
		</div>

		<div class="col">
			{% if error_message %}
                <p>
                    {{ error_message }}
                </p>
            {% endif %}
			<form action="{% url 'memories:save_memory' %}" method="post">
				{% csrf_token %}
				{{ form }}
				<br />
				<input name="submit" class="btn btn-success" type="submit" value="Сохранить" />
			</form>
		</div>
	  </div>
	</div>
{% endblock %}

mysite/memories/templates/memories/index.html
{% extends "base.html" %}

{% block content %}
    <body>
        <div class="container">
            <div class="row">
                <p>
                    Здравствуйте! Вы находитесь на сайте воспоминаний.
                    Если вы хотите сохранить или просмотреть свои впечатления о посещаяемых местах,
                    пожалуйста, авторизуйтесь через Facebook
                </p>
                <a href="{% url 'memories:personal_account' %}">Личная страница</a>
            </div>
        </div>

{% endblock %}

mysite/memories/templates/memories/user.html
{% extends "base.html" %}
{% block content %}
    <body>
    <div class="container">
        <div class="row">
            <p>Имя и фото пользователя</p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% if latest_memories_list %}
                <h3 align="center">Ваши воспоминания</h3> <br />
                <table class="table table-hover table-sm">
                  <thead>
                    <tr>
                      <th scope="col">Широта</th>
                      <th scope="col">Долгота</th>
                      <th scope="col">Название</th>
                      <th scope="col">Описание</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for memory in latest_memories_list %}
                        <tr>
                            <td>{{ memory.location_latitude }}</td>
                            <td>{{ memory.location_longitude }}</td>
                            <td>{{ memory.location_name }}</td>
                            <td>{{ memory.comment }}</td>
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
            {% else %}
                <p>У вас нет ни одного воспоминания</p>
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            <form action="{% url 'memories:form_add_memory' %}">
                <input type="submit" class="btn btn-success" value="Добавить воспоминание">
            </form>
        </div>
    </div>

{% endblock %}